#!/bin/bash

set -e

if [ ! -x /opt/csw/bin/pkgutil ]; then
       cat <<_EOF_ >/tmp/pkgadd-conf-$$
mail=
instance=overwrite
partial=nocheck
runlevel=nocheck
idepend=nocheck
rdepend=nocheck
space=nocheck
setuid=nocheck
conflict=nocheck
action=nocheck
networktimeout=60
networkretries=3
authentication=quit
keystore=/var/sadm/security
proxy=
basedir=default
_EOF_
    pkgadd -a /tmp/pkgadd-conf-$$ -d http://get.opencsw.org/now CSWpkgutil
    rm -f /tmp/pkgadd-conf-$$
fi

/opt/csw/bin/pkgutil -U
/opt/csw/bin/pkgutil -y -i python27
/opt/csw/bin/pkgutil -y -i py_pip
/opt/csw/bin/pkgutil -y -i py_argparse

# TODO: move to 'make install'
## Work-around for OpenCSW pip on Solaris 10 to avoid the need to
## mess with the PATH.
#for cli in afsutil; do
#    if [ -x /opt/csw/bin/$cli ]; then
#        test -h /usr/bin/$cli && rm -f /usr/bin/$cli
#        test -f /usr/bin/$cli || ln -s /opt/csw/bin/$cli /usr/bin/$cli
#    fi
#done
