#
# Standard errno system symbols for test cases. The values
# can vary by operating system.
#
# The following was generated by:
#
#   from os import errno
#   print "import os"
#   for c in errno.errorcode.keys():
#       print "{0} = os.errno.{0}".format(errno.errorcode[c])
#

import os
EPERM = os.errno.EPERM
ENOENT = os.errno.ENOENT
ESRCH = os.errno.ESRCH
EINTR = os.errno.EINTR
EIO = os.errno.EIO
ENXIO = os.errno.ENXIO
E2BIG = os.errno.E2BIG
ENOEXEC = os.errno.ENOEXEC
EBADF = os.errno.EBADF
ECHILD = os.errno.ECHILD
EAGAIN = os.errno.EAGAIN
ENOMEM = os.errno.ENOMEM
EACCES = os.errno.EACCES
EFAULT = os.errno.EFAULT
ENOTBLK = os.errno.ENOTBLK
EBUSY = os.errno.EBUSY
EEXIST = os.errno.EEXIST
EXDEV = os.errno.EXDEV
ENODEV = os.errno.ENODEV
ENOTDIR = os.errno.ENOTDIR
EISDIR = os.errno.EISDIR
EINVAL = os.errno.EINVAL
ENFILE = os.errno.ENFILE
EMFILE = os.errno.EMFILE
ENOTTY = os.errno.ENOTTY
ETXTBSY = os.errno.ETXTBSY
EFBIG = os.errno.EFBIG
ENOSPC = os.errno.ENOSPC
ESPIPE = os.errno.ESPIPE
EROFS = os.errno.EROFS
EMLINK = os.errno.EMLINK
EPIPE = os.errno.EPIPE
EDOM = os.errno.EDOM
ERANGE = os.errno.ERANGE
EDEADLOCK = os.errno.EDEADLOCK
ENAMETOOLONG = os.errno.ENAMETOOLONG
ENOLCK = os.errno.ENOLCK
ENOSYS = os.errno.ENOSYS
ENOTEMPTY = os.errno.ENOTEMPTY
ELOOP = os.errno.ELOOP
ENOMSG = os.errno.ENOMSG
EIDRM = os.errno.EIDRM
ECHRNG = os.errno.ECHRNG
EL2NSYNC = os.errno.EL2NSYNC
EL3HLT = os.errno.EL3HLT
EL3RST = os.errno.EL3RST
ELNRNG = os.errno.ELNRNG
EUNATCH = os.errno.EUNATCH
ENOCSI = os.errno.ENOCSI
EL2HLT = os.errno.EL2HLT
EBADE = os.errno.EBADE
EBADR = os.errno.EBADR
EXFULL = os.errno.EXFULL
ENOANO = os.errno.ENOANO
EBADRQC = os.errno.EBADRQC
EBADSLT = os.errno.EBADSLT
EBFONT = os.errno.EBFONT
ENOSTR = os.errno.ENOSTR
ENODATA = os.errno.ENODATA
ETIME = os.errno.ETIME
ENOSR = os.errno.ENOSR
ENONET = os.errno.ENONET
ENOPKG = os.errno.ENOPKG
EREMOTE = os.errno.EREMOTE
ENOLINK = os.errno.ENOLINK
EADV = os.errno.EADV
ESRMNT = os.errno.ESRMNT
ECOMM = os.errno.ECOMM
EPROTO = os.errno.EPROTO
EMULTIHOP = os.errno.EMULTIHOP
# undefined on Solaris; 
# comment out for now, since no test references it. 
# EDOTDOT = os.errno.EDOTDOT
EBADMSG = os.errno.EBADMSG
EOVERFLOW = os.errno.EOVERFLOW
ENOTUNIQ = os.errno.ENOTUNIQ
EBADFD = os.errno.EBADFD
EREMCHG = os.errno.EREMCHG
ELIBACC = os.errno.ELIBACC
ELIBBAD = os.errno.ELIBBAD
ELIBSCN = os.errno.ELIBSCN
ELIBMAX = os.errno.ELIBMAX
ELIBEXEC = os.errno.ELIBEXEC
EILSEQ = os.errno.EILSEQ
ERESTART = os.errno.ERESTART
ESTRPIPE = os.errno.ESTRPIPE
EUSERS = os.errno.EUSERS
ENOTSOCK = os.errno.ENOTSOCK
EDESTADDRREQ = os.errno.EDESTADDRREQ
EMSGSIZE = os.errno.EMSGSIZE
EPROTOTYPE = os.errno.EPROTOTYPE
ENOPROTOOPT = os.errno.ENOPROTOOPT
EPROTONOSUPPORT = os.errno.EPROTONOSUPPORT
ESOCKTNOSUPPORT = os.errno.ESOCKTNOSUPPORT
ENOTSUP = os.errno.ENOTSUP
EPFNOSUPPORT = os.errno.EPFNOSUPPORT
EAFNOSUPPORT = os.errno.EAFNOSUPPORT
EADDRINUSE = os.errno.EADDRINUSE
EADDRNOTAVAIL = os.errno.EADDRNOTAVAIL
ENETDOWN = os.errno.ENETDOWN
ENETUNREACH = os.errno.ENETUNREACH
ENETRESET = os.errno.ENETRESET
ECONNABORTED = os.errno.ECONNABORTED
ECONNRESET = os.errno.ECONNRESET
ENOBUFS = os.errno.ENOBUFS
EISCONN = os.errno.EISCONN
ENOTCONN = os.errno.ENOTCONN
ESHUTDOWN = os.errno.ESHUTDOWN
ETOOMANYREFS = os.errno.ETOOMANYREFS
ETIMEDOUT = os.errno.ETIMEDOUT
ECONNREFUSED = os.errno.ECONNREFUSED
EHOSTDOWN = os.errno.EHOSTDOWN
EHOSTUNREACH = os.errno.EHOSTUNREACH
EALREADY = os.errno.EALREADY
EINPROGRESS = os.errno.EINPROGRESS
ESTALE = os.errno.ESTALE
# undefined on Solaris; 
# comment out for now, since no test references it. 
# EUCLEAN = os.errno.EUCLEAN
# undefined on Solaris; 
# comment out for now, since no test references it. 
# ENOTNAM = os.errno.ENOTNAM
# undefined on Solaris; 
# comment out for now, since no test references it. 
# ENAVAIL = os.errno.ENAVAIL
# undefined on Solaris; 
# comment out for now, since no test references it. 
# EISNAM = os.errno.EISNAM
# undefined on Solaris; 
# comment out for now, since no test references it. 
# EREMOTEIO = os.errno.EREMOTEIO
EDQUOT = os.errno.EDQUOT
