#!/bin/sh

apt-get install -q -y python python-pip

if python -c 'import argparse' >/dev/null 2>/dev/null; then
    : # argparse is in the standard library
else
    apt-get install -q -y python-argparse
fi

