#!/bin/sh

die() {
    echo "$1" >&2
    exit 1
}

if [ ! -x /opt/csw/bin/pkgutil ]; then
       cat <<_EOF_ >/tmp/pkgadd-conf-$$
mail=
instance=overwrite
partial=nocheck
runlevel=nocheck
idepend=nocheck
rdepend=nocheck
space=nocheck
setuid=nocheck
conflict=nocheck
action=nocheck
networktimeout=60
networkretries=3
authentication=quit
keystore=/var/sadm/security
proxy=
basedir=default
_EOF_
    pkgadd -a /tmp/pkgadd-conf-$$ -d http://get.opencsw.org/now CSWpkgutil || die "Failed to install pkgutil."
    rm -f /tmp/pkgadd-conf-$$
fi

/opt/csw/bin/pkgutil -U || die "Failed to update pkgutil."
/opt/csw/bin/pkgutil -y -i python27 || die "Failed to install python27."
/opt/csw/bin/pkgutil -y -i py_pip || die "Failed to install py_pip."
/opt/csw/bin/pkgutil -y -i py_argparse || die "Failed to install py_argparse."

