#!/usr/bin/env python
# Compatibility wrapper.
import os
import sys
sys.stderr.write("WARNING: afs-robotest is deprecated: use afsrobot\n")
args = sys.argv[1:]
args.insert(0, 'afsrobot')
os.execvp('afsrobot', args)
