---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Add the hypervisor to the in-memory inventory.
      add_host:
        name: hypervisor
        ansible_host: "{{ molecule_yml.driver.host }}"
        ansible_python_interpreter: "{{ molecule_yml.driver.python_interpreter }}"

- name: Create
  hosts: hypervisor
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create instance(s).
      virt_up:
        state: up
        name: "{{ item.name }}"
        template: "{{ item.template }}"
        sshdir: "{{ molecule_ephemeral_directory }}"
      environment:
        LIBVIRT_DEFAULT_URI: "{{ molecule_yml.driver.libvirt_uri | default('qemu:///session') }}"
      loop: "{{ molecule_yml.platforms }}"
      register: virt_up

    - name: Fetch ssh identity files.
      block:
        - name: Fetch private key files.
          fetch:
            flat: yes
            src: "{{ item.remote_identity_file }}"
            dest: "{{ item.server.identity_file }}"
          loop: "{{ virt_up.results }}"

        - name: Fetch public key files.
          fetch:
            flat: yes
            src: "{{ item.remote_identity_file }}.pub"
            dest: "{{ item.server.identity_file }}.pub"
          loop: "{{ virt_up.results }}"

        - name: Set private key file permissions.
          local_action:
            module: file
            state: file
            mode: "0600"
            path: "{{ item.server.identity_file }}"
          loop: "{{ virt_up.results }}"

        - name: Set public key file permissions.
          local_action:
            module: file
            state: file
            mode: "0644"
            path: "{{ item.server.identity_file }}.pub"
          loop: "{{ virt_up.results }}"

    - name: Convert results to instance config.
      set_fact:
        instance_conf: "{{ virt_up.results | map(attribute='server') | list }}"

    #- debug:
    #    var: instance_conf

    - name: Write instance config
      local_action:
        module: copy
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
