#!/bin/sh
set -e
PATH=.:./setup:$PATH source linux-functions.sh

# System setup
create_tester "$AFSROBOT_USERNAME" "$SETUP_GROUP"
fixup_etc_hosts "$AFSROBOT_IFDEVICE"

# Install prereqs
export PIP_DISABLE_PIP_VERSION_CHECK=1
zypper install -y python python-pip
pip install --upgrade robotframework
