#!/bin/sh
set -e
PATH=.:./setup:$PATH source linux-functions.sh

# System setup
create_tester "$AFSROBOT_USERNAME" "$SETUP_GROUP"
fixup_etc_hosts "$AFSROBOT_IFDEVICE"

# Install prereqs
export PIP_DISABLE_PIP_VERSION_CHECK=1

yum install -q -y epel-release
yum install -q -y python python-pip

if ! python -c 'import argparse' >/dev/null 2>/dev/null; then
    yum install -q -y python-argparse
fi

pip install --upgrade robotframework
